---
# Source: loki-stack/charts/loki/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-0.16.0
    heritage: Tiller
    release: release-name
  name: release-name-loki
  namespace: default

