---
# Source: loki-stack/charts/promtail/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-promtail
  namespace: default
  labels:
    app: promtail
    chart: promtail-0.12.3
    heritage: Tiller
    release: release-name
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [release-name-promtail]
