---
# Source: loki-stack/charts/prometheus/templates/alertmanager-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: release-name
    chart: prometheus-8.11.6
    heritage: Tiller
  name: release-name-prometheus-alertmanager