---
# Source: loki-stack/charts/prometheus/templates/node-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    
  labels:
    component: "node-exporter"
    app: prometheus
    release: release-name
    chart: prometheus-8.11.6
    heritage: Tiller
  name: release-name-prometheus-node-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: release-name
  type: "ClusterIP"